# Use postgres/example user/password credentials
version: '3.9'

name: goserve
services:
  # frontend:
  #   build: ./frontend
  #   # image: node:latest
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   ports:
  #     - 3000:80
  #   depends_on:
  #     - backend

  # backend:
  #   build: ./backend
  #   network_mode: "host"
  #   # image: golang:latest
  #   volumes:
  #     - ./backend:/backend
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - postgres


  postgres:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: v1
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

