# Use postgres/example user/password credentials
version: '3.9'

name: goserve
services:
  app:
    build: ./
    environment:
      DB_URL: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: v1
    volumes:
      - ./app:/app
    ports:
      - 8081:8081
      - 3000:80
    networks:
      - goserve-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: v1
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - goserve-network

networks:
  goserve-network:
