// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dashboard struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	Rows  int     `json:"rows"`
	Cols  int     `json:"cols"`
	Tiles []*Tile `json:"tiles"`
}

type Mutation struct {
}

type NewDashboard struct {
	Name string `json:"name"`
	Rows *int   `json:"rows,omitempty"`
	Cols *int   `json:"cols,omitempty"`
}

type NewTemplate struct {
	Name      string         `json:"name"`
	Data      string         `json:"data"`
	Width     *int           `json:"width,omitempty"`
	Height    *int           `json:"height,omitempty"`
	Variables []*NewVariable `json:"variables"`
}

type NewTile struct {
	Name        string         `json:"name"`
	Row         int            `json:"row"`
	Col         int            `json:"col"`
	Width       int            `json:"width"`
	Height      int            `json:"height"`
	DashboardID *int           `json:"dashboardId,omitempty"`
	TemplateID  *int           `json:"templateId,omitempty"`
	Variables   []*NewVariable `json:"variables"`
}

type NewVariable struct {
	Name       string  `json:"name"`
	Value      *string `json:"value,omitempty"`
	Default    *string `json:"default,omitempty"`
	TemplateID *int    `json:"template_id,omitempty"`
	TileID     *int    `json:"tile_id,omitempty"`
}

type Query struct {
}

type Template struct {
	ID        int         `json:"id"`
	Name      string      `json:"name"`
	Data      string      `json:"data"`
	Width     int         `json:"width"`
	Height    int         `json:"height"`
	Variables []*Variable `json:"variables,omitempty"`
}

type Tile struct {
	ID        int         `json:"id"`
	Name      string      `json:"name"`
	Row       int         `json:"row"`
	Col       int         `json:"col"`
	Width     int         `json:"width"`
	Height    int         `json:"height"`
	Template  *Template   `json:"template"`
	Variables []*Variable `json:"variables"`
}

type Variable struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Value   string `json:"value"`
	Default string `json:"default"`
}
