// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dashboard struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Rows        int     `json:"rows"`
	Cols        int     `json:"cols"`
	Tiles       []*Tile `json:"tiles"`
}

type Mutation struct {
}

type NewDashboard struct {
	Name string `json:"name"`
}

type NewTile struct {
	Name        string  `json:"name"`
	DashboardID string  `json:"dashboard_id"`
	Description *string `json:"description,omitempty"`
	Data        string  `json:"data"`
	Row         int     `json:"row"`
	Col         int     `json:"col"`
	Width       int     `json:"width"`
	Height      int     `json:"height"`
}

type Query struct {
}

type Tile struct {
	ID          int        `json:"id"`
	Dashboard   *Dashboard `json:"dashboard"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Data        string     `json:"data"`
	Row         int        `json:"row"`
	Col         int        `json:"col"`
	Width       int        `json:"width"`
	Height      int        `json:"height"`
}

type User struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Email      string       `json:"email"`
	Password   string       `json:"password"`
	Dashboards []*Dashboard `json:"dashboards"`
}
