//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Template struct {
	ID     int32 `sql:"primary_key"`
	Name   string
	Data   string
	Width  int32
	Height int32
}
