//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Tile struct {
	ID          int32 `sql:"primary_key"`
	Name        string
	Description *string
	Row         int32
	Col         int32
	Data        string
	Width       int32
	Height      int32
	DashboardID int32
}
